### ISSUE TITLE
Update revancify method

### ISSUE THREAD

**Issue by decipher3114** [TeaEndsAcronyms/Material-You-Apps#17]
For installation, you must refer users to the repository instead.

There is new method for installation of revancify.

**Comment by TeaEndsAcronyms** [comment]
Nevermind i found it, May i ask whats new?

**Comment by TeaEndsAcronyms** [comment]
> can you send me a link of the repository?

Nevermind i found it, May i ask whats new?

**Comment by TeaEndsAcronyms** [comment]
Updated!
