### ISSUE TITLE
Incorrect Category for todoify

### ISSUE THREAD

**Issue by milindgoel15** [TeaEndsAcronyms/Material-You-Apps#23]
Thanks for adding my app to your list. 

But you have added it in the foss category. The app is closed source by nature. Github is only used for providing updates and maintaining issue repositories for all my apps.

Can you please create a new category for every closed source app? Adding them to Foss would be kinda misleading.

**Comment by TeaEndsAcronyms** [comment]
Ok! ill edit it as soon as i can. (im a bit busy), thank you for informing me!

**Comment by TeaEndsAcronyms** [comment]
Fixed!
