### ISSUE TITLE
Typo in app name

### ISSUE THREAD

**Issue by sadellie** [TeaEndsAcronyms/Material-You-Apps#9]
You have a typo here:
https://github.com/TeaEndsAcronyms/Material-You-Apps/blob/59fb5f25060bc3b89290a142c90a9d2f2d55e2da/README.md?plain=1#L417

It should be `Unitto` instead of `Unnito`

**Comment by TeaEndsAcronyms** [comment]
Thanks for mentioning! will fix! :)
